/* 自動生成ファイル: build_sw.py で作り直してください */
const CACHE = "fumekuri-85c38d67dadc";
const PRECACHE = [
"./",
"app.js",
"doc.css",
"icons/apple-touch-icon.png",
"icons/icon-192.png",
"icons/icon-512.png",
"icons/icon-maskable-512.png",
"index.html",
"licenses.html",
"licenses/LICENSE_LIBERATION.txt",
"licenses/cmaps-LICENSE.txt",
"licenses/foxit-LICENSE.txt",
"licenses/pako-LICENSE.txt",
"licenses/pdf-lib-LICENSE.txt",
"licenses/pdfjs-LICENSE.txt",
"licenses/standard-fonts-LICENSE.txt",
"licenses/upng-LICENSE.txt",
"manifest.webmanifest",
"policy.html",
"styles.css",
"vendor/cmaps/78-EUC-H.bcmap",
"vendor/cmaps/78-EUC-V.bcmap",
"vendor/cmaps/78-H.bcmap",
"vendor/cmaps/78-RKSJ-H.bcmap",
"vendor/cmaps/78-RKSJ-V.bcmap",
"vendor/cmaps/78-V.bcmap",
"vendor/cmaps/78ms-RKSJ-H.bcmap",
"vendor/cmaps/78ms-RKSJ-V.bcmap",
"vendor/cmaps/83pv-RKSJ-H.bcmap",
"vendor/cmaps/90ms-RKSJ-H.bcmap",
"vendor/cmaps/90ms-RKSJ-V.bcmap",
"vendor/cmaps/90msp-RKSJ-H.bcmap",
"vendor/cmaps/90msp-RKSJ-V.bcmap",
"vendor/cmaps/90pv-RKSJ-H.bcmap",
"vendor/cmaps/90pv-RKSJ-V.bcmap",
"vendor/cmaps/Add-H.bcmap",
"vendor/cmaps/Add-RKSJ-H.bcmap",
"vendor/cmaps/Add-RKSJ-V.bcmap",
"vendor/cmaps/Add-V.bcmap",
"vendor/cmaps/Adobe-CNS1-0.bcmap",
"vendor/cmaps/Adobe-CNS1-1.bcmap",
"vendor/cmaps/Adobe-CNS1-2.bcmap",
"vendor/cmaps/Adobe-CNS1-3.bcmap",
"vendor/cmaps/Adobe-CNS1-4.bcmap",
"vendor/cmaps/Adobe-CNS1-5.bcmap",
"vendor/cmaps/Adobe-CNS1-6.bcmap",
"vendor/cmaps/Adobe-CNS1-UCS2.bcmap",
"vendor/cmaps/Adobe-GB1-0.bcmap",
"vendor/cmaps/Adobe-GB1-1.bcmap",
"vendor/cmaps/Adobe-GB1-2.bcmap",
"vendor/cmaps/Adobe-GB1-3.bcmap",
"vendor/cmaps/Adobe-GB1-4.bcmap",
"vendor/cmaps/Adobe-GB1-5.bcmap",
"vendor/cmaps/Adobe-GB1-UCS2.bcmap",
"vendor/cmaps/Adobe-Japan1-0.bcmap",
"vendor/cmaps/Adobe-Japan1-1.bcmap",
"vendor/cmaps/Adobe-Japan1-2.bcmap",
"vendor/cmaps/Adobe-Japan1-3.bcmap",
"vendor/cmaps/Adobe-Japan1-4.bcmap",
"vendor/cmaps/Adobe-Japan1-5.bcmap",
"vendor/cmaps/Adobe-Japan1-6.bcmap",
"vendor/cmaps/Adobe-Japan1-UCS2.bcmap",
"vendor/cmaps/Adobe-Korea1-0.bcmap",
"vendor/cmaps/Adobe-Korea1-1.bcmap",
"vendor/cmaps/Adobe-Korea1-2.bcmap",
"vendor/cmaps/Adobe-Korea1-UCS2.bcmap",
"vendor/cmaps/B5-H.bcmap",
"vendor/cmaps/B5-V.bcmap",
"vendor/cmaps/B5pc-H.bcmap",
"vendor/cmaps/B5pc-V.bcmap",
"vendor/cmaps/CNS-EUC-H.bcmap",
"vendor/cmaps/CNS-EUC-V.bcmap",
"vendor/cmaps/CNS1-H.bcmap",
"vendor/cmaps/CNS1-V.bcmap",
"vendor/cmaps/CNS2-H.bcmap",
"vendor/cmaps/CNS2-V.bcmap",
"vendor/cmaps/ETHK-B5-H.bcmap",
"vendor/cmaps/ETHK-B5-V.bcmap",
"vendor/cmaps/ETen-B5-H.bcmap",
"vendor/cmaps/ETen-B5-V.bcmap",
"vendor/cmaps/ETenms-B5-H.bcmap",
"vendor/cmaps/ETenms-B5-V.bcmap",
"vendor/cmaps/EUC-H.bcmap",
"vendor/cmaps/EUC-V.bcmap",
"vendor/cmaps/Ext-H.bcmap",
"vendor/cmaps/Ext-RKSJ-H.bcmap",
"vendor/cmaps/Ext-RKSJ-V.bcmap",
"vendor/cmaps/Ext-V.bcmap",
"vendor/cmaps/GB-EUC-H.bcmap",
"vendor/cmaps/GB-EUC-V.bcmap",
"vendor/cmaps/GB-H.bcmap",
"vendor/cmaps/GB-V.bcmap",
"vendor/cmaps/GBK-EUC-H.bcmap",
"vendor/cmaps/GBK-EUC-V.bcmap",
"vendor/cmaps/GBK2K-H.bcmap",
"vendor/cmaps/GBK2K-V.bcmap",
"vendor/cmaps/GBKp-EUC-H.bcmap",
"vendor/cmaps/GBKp-EUC-V.bcmap",
"vendor/cmaps/GBT-EUC-H.bcmap",
"vendor/cmaps/GBT-EUC-V.bcmap",
"vendor/cmaps/GBT-H.bcmap",
"vendor/cmaps/GBT-V.bcmap",
"vendor/cmaps/GBTpc-EUC-H.bcmap",
"vendor/cmaps/GBTpc-EUC-V.bcmap",
"vendor/cmaps/GBpc-EUC-H.bcmap",
"vendor/cmaps/GBpc-EUC-V.bcmap",
"vendor/cmaps/H.bcmap",
"vendor/cmaps/HKdla-B5-H.bcmap",
"vendor/cmaps/HKdla-B5-V.bcmap",
"vendor/cmaps/HKdlb-B5-H.bcmap",
"vendor/cmaps/HKdlb-B5-V.bcmap",
"vendor/cmaps/HKgccs-B5-H.bcmap",
"vendor/cmaps/HKgccs-B5-V.bcmap",
"vendor/cmaps/HKm314-B5-H.bcmap",
"vendor/cmaps/HKm314-B5-V.bcmap",
"vendor/cmaps/HKm471-B5-H.bcmap",
"vendor/cmaps/HKm471-B5-V.bcmap",
"vendor/cmaps/HKscs-B5-H.bcmap",
"vendor/cmaps/HKscs-B5-V.bcmap",
"vendor/cmaps/Hankaku.bcmap",
"vendor/cmaps/Hiragana.bcmap",
"vendor/cmaps/KSC-EUC-H.bcmap",
"vendor/cmaps/KSC-EUC-V.bcmap",
"vendor/cmaps/KSC-H.bcmap",
"vendor/cmaps/KSC-Johab-H.bcmap",
"vendor/cmaps/KSC-Johab-V.bcmap",
"vendor/cmaps/KSC-V.bcmap",
"vendor/cmaps/KSCms-UHC-H.bcmap",
"vendor/cmaps/KSCms-UHC-HW-H.bcmap",
"vendor/cmaps/KSCms-UHC-HW-V.bcmap",
"vendor/cmaps/KSCms-UHC-V.bcmap",
"vendor/cmaps/KSCpc-EUC-H.bcmap",
"vendor/cmaps/KSCpc-EUC-V.bcmap",
"vendor/cmaps/Katakana.bcmap",
"vendor/cmaps/LICENSE",
"vendor/cmaps/NWP-H.bcmap",
"vendor/cmaps/NWP-V.bcmap",
"vendor/cmaps/RKSJ-H.bcmap",
"vendor/cmaps/RKSJ-V.bcmap",
"vendor/cmaps/Roman.bcmap",
"vendor/cmaps/UniCNS-UCS2-H.bcmap",
"vendor/cmaps/UniCNS-UCS2-V.bcmap",
"vendor/cmaps/UniCNS-UTF16-H.bcmap",
"vendor/cmaps/UniCNS-UTF16-V.bcmap",
"vendor/cmaps/UniCNS-UTF32-H.bcmap",
"vendor/cmaps/UniCNS-UTF32-V.bcmap",
"vendor/cmaps/UniCNS-UTF8-H.bcmap",
"vendor/cmaps/UniCNS-UTF8-V.bcmap",
"vendor/cmaps/UniGB-UCS2-H.bcmap",
"vendor/cmaps/UniGB-UCS2-V.bcmap",
"vendor/cmaps/UniGB-UTF16-H.bcmap",
"vendor/cmaps/UniGB-UTF16-V.bcmap",
"vendor/cmaps/UniGB-UTF32-H.bcmap",
"vendor/cmaps/UniGB-UTF32-V.bcmap",
"vendor/cmaps/UniGB-UTF8-H.bcmap",
"vendor/cmaps/UniGB-UTF8-V.bcmap",
"vendor/cmaps/UniJIS-UCS2-H.bcmap",
"vendor/cmaps/UniJIS-UCS2-HW-H.bcmap",
"vendor/cmaps/UniJIS-UCS2-HW-V.bcmap",
"vendor/cmaps/UniJIS-UCS2-V.bcmap",
"vendor/cmaps/UniJIS-UTF16-H.bcmap",
"vendor/cmaps/UniJIS-UTF16-V.bcmap",
"vendor/cmaps/UniJIS-UTF32-H.bcmap",
"vendor/cmaps/UniJIS-UTF32-V.bcmap",
"vendor/cmaps/UniJIS-UTF8-H.bcmap",
"vendor/cmaps/UniJIS-UTF8-V.bcmap",
"vendor/cmaps/UniJIS2004-UTF16-H.bcmap",
"vendor/cmaps/UniJIS2004-UTF16-V.bcmap",
"vendor/cmaps/UniJIS2004-UTF32-H.bcmap",
"vendor/cmaps/UniJIS2004-UTF32-V.bcmap",
"vendor/cmaps/UniJIS2004-UTF8-H.bcmap",
"vendor/cmaps/UniJIS2004-UTF8-V.bcmap",
"vendor/cmaps/UniJISPro-UCS2-HW-V.bcmap",
"vendor/cmaps/UniJISPro-UCS2-V.bcmap",
"vendor/cmaps/UniJISPro-UTF8-V.bcmap",
"vendor/cmaps/UniJISX0213-UTF32-H.bcmap",
"vendor/cmaps/UniJISX0213-UTF32-V.bcmap",
"vendor/cmaps/UniJISX02132004-UTF32-H.bcmap",
"vendor/cmaps/UniJISX02132004-UTF32-V.bcmap",
"vendor/cmaps/UniKS-UCS2-H.bcmap",
"vendor/cmaps/UniKS-UCS2-V.bcmap",
"vendor/cmaps/UniKS-UTF16-H.bcmap",
"vendor/cmaps/UniKS-UTF16-V.bcmap",
"vendor/cmaps/UniKS-UTF32-H.bcmap",
"vendor/cmaps/UniKS-UTF32-V.bcmap",
"vendor/cmaps/UniKS-UTF8-H.bcmap",
"vendor/cmaps/UniKS-UTF8-V.bcmap",
"vendor/cmaps/V.bcmap",
"vendor/cmaps/WP-Symbol.bcmap",
"vendor/pdf-lib.min.js",
"vendor/pdf.min.js",
"vendor/pdf.worker.min.js",
"vendor/standard_fonts/FoxitDingbats.pfb",
"vendor/standard_fonts/FoxitFixed.pfb",
"vendor/standard_fonts/FoxitFixedBold.pfb",
"vendor/standard_fonts/FoxitFixedBoldItalic.pfb",
"vendor/standard_fonts/FoxitFixedItalic.pfb",
"vendor/standard_fonts/FoxitSerif.pfb",
"vendor/standard_fonts/FoxitSerifBold.pfb",
"vendor/standard_fonts/FoxitSerifBoldItalic.pfb",
"vendor/standard_fonts/FoxitSerifItalic.pfb",
"vendor/standard_fonts/FoxitSymbol.pfb",
"vendor/standard_fonts/LICENSE_FOXIT",
"vendor/standard_fonts/LiberationSans-Bold.ttf",
"vendor/standard_fonts/LiberationSans-BoldItalic.ttf",
"vendor/standard_fonts/LiberationSans-Italic.ttf",
"vendor/standard_fonts/LiberationSans-Regular.ttf"
];

self.addEventListener('install', e => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    // fetch in small batches and store one by one (addAll is fragile on some browsers)
    for (let i = 0; i < PRECACHE.length; i += 16) {
      await Promise.all(PRECACHE.slice(i, i + 16).map(async u => {
        const res = await fetch(u, { cache: 'reload' });
        if (!res.ok) throw new Error('precache failed: ' + u);
        await c.put(u, res);
      }));
    }
    await self.skipWaiting();
  })());
});
self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('fumekuri-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => {
      if (hit) return hit;
      return fetch(req).then(res => {
        if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
        return res;
      }).catch(() => req.mode === 'navigate' ? caches.match('./index.html') : Response.error());
    })
  );
});
